### ISSUE TITLE
Skill not showing name

### ISSUE THREAD

**Issue by PoiDoex8** [Iuke121/NaoParse#1]
Currently giant full swing is not showing a name when it is on the "highest damage" list
also the parser does not seem to account for reapers

**Comment by LukasTD** [comment]
> Currently giant full swing is not showing a name when it is on the "highest damage" list
> also the parser does not seem to account for reapers

Hey! I will take a look at Giant Full Swing, I personally don't have a giant so I couldn't catch that yet.
In regards to reaper, this is both intentional and even if it wasn't I don't think it's possible to solve from packets. It is intentional due to the fact that reaper is very RNG, and may not be an accurate representation of a player's gameplay to damage performance. And the reason why I don't think it's possible to solve with packets, is because the reaper is only an effect on your screen, and the mob's HP just gets subtracted from the reaper damage, and the result of that is that it's impossible to differentiate your reaper and other players' reapers. I've debated adding a row for "everyone's reapers" but I haven't decided to do something like that yet, as I haven't seen the point yet.

EDIT: giant skills fixed here https://github.com/Iuke121/NaoParse/commit/e7f9b8cc923d34b6c2fe5733d0e330daaf4c8b3f
